apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: fdk-dataservice-harvester-etl
  name: fdk-dataservice-harvester-etl
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      fdk.service: fdk-dataservice-harvester-etl
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: fdk-dataservice-harvester-etl
    spec:
      containers:
      - env:
          - name: TO_BE_UPDATED
            value: {{ required "Missing value TO_BE_UPDATED" .Values.TO_BE_UPDATED | quote }}
        image: {{ required "Missing value DOCKER_IMAGE_NAME" .Values.DOCKER_IMAGE_NAME }}
        imagePullPolicy: Always
        name: fdk-dataservice-harvester-etl
        resources:
          requests:
            memory: {{ required "Missing value FDK_DATASERVICE_HARVESTER_ETL_MEMORY" .Values.FDK_DATASERVICE_HARVESTER_ETL_MEMORY | quote }}
      restartPolicy: Always
status: {}
