name: Build and deploy to staging on push

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Deploy to staging environment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e  # v1

    - name: Setup python environment
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
      with:
          python-version: '3.12'

    - name: Setup gcloud CLI
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@b94035a6aac71cdacf6e682bbbef2e927960f8ac  # master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_KEY }}

    - run: gcloud auth configure-docker

    - name: Build Docker image with GitHub commit sha tag and staging tag
      run: docker build . -t eu.gcr.io/digdir-fdk-infra/fdk-dataservice-harvester-etl:staging_latest -t eu.gcr.io/digdir-fdk-infra/fdk-dataservice-harvester-etl:$GITHUB_SHA

    - name: Publish docker image to Google Cloud
      run: docker -- push eu.gcr.io/digdir-fdk-infra/fdk-dataservice-harvester-etl

    - name: Apply Helm template
      uses: stefanprodan/kube-tools@0d241188296aee8e513e9597ba7eede46f6155ef  # v1.7.2
      with:
        helm: 2.14.3
        command: |
          helm init --client-only
          helm repo add fdk-dataservice-harvester-etl https://informasjonsforvaltning.github.io/fdk-dataservice-harvester-etl/
          helm fetch --untar --untardir ./helm fdk-dataservice-harvester-etl/fdk-dataservice-harvester-etl
          helm template --set DOCKER_IMAGE_NAME="eu.gcr.io/digdir-fdk-infra/fdk-dataservice-harvester-etl:$GITHUB_SHA" -f ./helm-sources/values/staging.yaml ./helm/fdk-dataservice-harvester-etl/  > ./kubectlapply.yaml
          chmod o+w ./kubectlapply.yaml
          cat kubectlapply.yaml

    - name: Get kubeconfig file from GKE
      uses: machine-learning-apps/gke-kubeconfig@89993c4e45e041a1432bc1676a4fa35ec3ec37c8  # master
      with:
        application_credentials: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
        project_id: digdir-fdk-dev
        location_zone: europe-north1-a
        cluster_name: digdir-fdk-dev

    - name: Deploy to staging
      uses: docker://bitnami/kubectl@sha256:3220dcc839f55be732a29548043a1ddf635a0dd6c8781b0f2a0bcdc19029c7d3  # latest
      env:
        KUBECONFIG: '/github/workspace/.kube/config'
      with:
        args: "apply -f ./kubectlapply.yaml --force"
